name: todo2ddd

services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongo
    restart: on-failure
    environment:
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_DATABASE=todo2ddd'
    ports:
      - '27017:27017'
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    restart: on-failure
    environment:
      - 'POSTGRES_USER=todo2ddd'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_DB=todo2ddd'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    container_name: redis
    restart: on-failure
    ports:
      - '6379:6379'
